### ISSUE TITLE
tweets_dave.csv

### ISSUE THREAD

**Issue by suyi19890508** [dgrtwo/tidy-text-mining#17]
tweets_dave.csv is in wrong format

**Comment by juliasilge** [comment]
Can you give me more detail on what kind of trouble you are having? This is the actual file that we use to build [this chapter of the book](http://tidytextmining.com/twitter.html), as you can see i[n the code here](https://github.com/dgrtwo/tidy-text-mining/blob/9114aa3bfe93c345c6a2fb42a22497c24a4d6292/08-tweet-archives.Rmd#getting-the-data-and-distribution-of-tweets).

**Comment by suyi19890508** [comment]
Thanks very much. I download tweets_dave.csv from the URL 'https://github.com/dgrtwo/tidy-text-mining/tree/master/data', which has only one column. I also download tweets_julia.csv from the same URL, but which has ten columns. So I think maybe some questions with it.
I could find ten columns when I open tweets_dave.csv online, however, the web page say :"We can't make this file beautiful and searchable because it's too large."
