### ISSUE TITLE
Set up auto-compiling on Travis to GitHub Pages

### ISSUE THREAD

**Issue by dgrtwo** [dgrtwo/tidy-text-mining#2]
I'd like to get the current HTML up on GitHub pages; it would be a great way to share work in progress and to review what most needs to be done. We could also have Travis build it automatically upon pushing.

[There's a guide to GitHub + Travis here](https://bookdown.org/yihui/bookdown/github.html): I started doing this on the gh-pages branch but honestly got a little turned around. Putting Issue here as a suggestion to either of us when time and interest arises.

(Right now it is technically visible at the awful URL of [http://varianceexplained.org/tidy-text-mining/_book/intro.html](http://varianceexplained.org/tidy-text-mining/_book/intro.html) with zero CSS, which- yuck!)

**Comment by juliasilge** [comment]
Jenny has done this with her [Happy Git with R](http://happygitwithr.com/) site, so it is doable.

GitHub repo: https://github.com/jennybc/happy-git-with-r

We should get a URL!

**Comment by juliasilge** [comment]
Here's another example, with slightly different .travis.yml and scripts to build the book:

GitHub repo: https://github.com/csgillespie/efficientR
Rendered site: https://csgillespie.github.io/efficientR/

What I really don't understand right now is why I can't get the book to build an `index.html` from the `index.Rmd`. Both of the above examples have them.

**Comment by juliasilge** [comment]
So I don't know that we're really at a stage where all of this will work, but there is some stuff that you need to do because this is your repo, @dgrtwo. You need to do the parts where you grant Travis write access to your GitHub repository. I believe you need to create a token and encrypt it on Travis, and then put it in `.travis.yml`.

Things still aren't quite set up to work yet, because

- I just changed `new_session` but haven't gone through the first chapters to fix everything and
- I don't know that `DESCRIPTION` has all the packages that Travis needs to build the book.

But... it's a start? :grimacing:

**Comment by juliasilge** [comment]
Also, I would just like to state for the record that a gh-pages branch always makes me feel like I have gone to an ALTERNATE UNIVERSE.

(It's the same repository. But what is here?! Something completely different!)

**Comment by dgrtwo** [comment]
Doing so now!

Incidentally it turns out that as of about a week ago [you can use a doc/ folder instead of a gh-pages branch](https://twitter.com/thejameskyle/status/768258617346621440)! Don't know if that would have helped

**Comment by dgrtwo** [comment]
Done in 0fea3c64921cbe3e3320192771b4f41be95b6f60

When will we know if it worked?

**Comment by juliasilge** [comment]
Well, I don't think it can build right *successfully* right now but we should at least be able to see it try to build, just like an R package. We should be able to see it here:
https://travis-ci.org/dgrtwo/tidy-text-mining
When I go there, it looks like the repo maybe isn't clicked "on" yet? Have you flipped the switch from off to on? I don't think I can do it (even though I have write access to the repo).

**Comment by dgrtwo** [comment]
OK I hit the start button and gave a test commit, so now it's off to the races.

This is gonna take a long time but I think we'll be able to set up the cache to stay around.

See my email earlier btw?

**Comment by juliasilge** [comment]
Ah, there is another part you need to do here on the repo for the custom domain. Change something in the settings to add tidytextmining.com: https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

**Comment by dgrtwo** [comment]
Done

**Comment by juliasilge** [comment]
I think this is good now, right? I'm going to close this.

**Comment by dgrtwo** [comment]
👍👍
