### ISSUE TITLE
add the pdf/ebook to the repo/website

### ISSUE THREAD

**Issue by zippeurfou** [dgrtwo/tidy-text-mining#20]
Hi, this might seems like a trivial request that I could easily do by myself (it is even commented in the code for the pdf part and [this function](http://tidytextmining.com/) would do the ebook).
However, I believe that it might be useful to have it for people to download on the  index of the [website](http://tidytextmining.com/) as many people like to read the book "offline" in the subway or else.
PS: not really an issue but an enhancement suggestion
PS2: I really like the book. If I had another suggestion to say it would be maybe to include some more advanced methods or at least literature/package to go forward (I am a big fan of the `qdap` package, also `sentimentr::highlight` is a neat tool that could come handy for the book at some point).

**Comment by juliasilge** [comment]
Thank you so much for reading the book! We are super excited to be publishing our book with O'Reilly and we have reached an agreement to keep the [HTML version online](http://tidytextmining.com/), but O'Reilly is going to be making the PDF/eBook versions (and paper versions!) of the book available. We are committed to keeping the code to make the book open and free, so definitely go ahead and make full use of that!
