### ISSUE TITLE
Suggestion: gutenberg_download" cannot download the free book

### ISSUE THREAD

**Issue by wangcug** [dgrtwo/tidy-text-mining#26]
In chapter 1.5,  the function " gutenberg_download" cannot download the free book by `hgwells <- gutenberg_download(c(35, 36, 5230, 159))` the defaults mirror appears to be down. It is needed to update the mirror address  `hgwells <- gutenberg_download(c(35, 36, 5230, 159), mirror = "http://mirrors.xmission.com/gutenberg/")`   The more infromation can be seen from [https://github.com/ropenscilabs/gutenbergr/issues/8](url)

**Comment by dgrtwo** [comment]
This is a gutenbergr issue rather than the text mining book so I'll close this one. The good news is it's fixed in the dev version of gutenbergr (soon to be on CRAN).
