### ISSUE TITLE
Travis + gutenbergr

### ISSUE THREAD

**Issue by juliasilge** [dgrtwo/tidy-text-mining#3]
The latest commit I just pushed failed because of our old friend, a 403 HTTP error from Project Gutenberg. Do we want to do the quasi-cheater thing we did with the vignettes in tidytext to get this to build on Travis? Store these things as data objects in `data/` so that we don't have to actually call Project Gutenberg from Travis?

**Comment by dgrtwo** [comment]
Yep, I think that's the way to go!

**Comment by juliasilge** [comment]
So this is good now? I am closing it.
