### ISSUE TITLE
Chapter 2 - bing _and_nrc 

### ISSUE THREAD

**Issue by t1ber1us** [dgrtwo/tidy-text-mining#30]
Hi,
Working from the web version of your book, and looking forward to getting a 'real' copy when it is out.

In chapter 2, when you are doing sentiment analysis on pride and prejudice, you create a joint bing_and_nrc vector, but the code seems to go awry at the end of the line :

mutate(method="Bing et al."), 
because of the ',' on the end (screenshot of code also attached).

I have managed to get a working version by separating the two variables, but can see your version is more elegant. How should this code look?

Thanks,
<img width="383" alt="code segment" src="https://cloud.githubusercontent.com/assets/28763671/26169558/04aedd10-3b36-11e7-9153-407d6f018733.PNG">

**Comment by juliasilge** [comment]
Hello! The online version of this book is generated with the actual code you see on the website via R Markdown and bookdown; you can see how that works here in this very repo. :smiley:

So we know that the code on the [website](http://tidytextmining.com/sentiment.html#comparing-the-three-sentiment-dictionaries) works; you can see the the [R Markdown file here](https://github.com/dgrtwo/tidy-text-mining/blob/master/02-sentiment-analysis.Rmd). Probably there is some issue in how you are copying or translating the code?

**Comment by suyi19890508** [comment]
Thanks! Tt's my pleasure!

**Comment by t1ber1us** [comment]
Thanks. I see now where I was going wrong (it was a knock-on effect, the bind_rows command of the first line doesn't have a closing bracket, Rstudio screamed as I entered it so I 'fixed' it by inserting one, meaning that the comma on the 'mutate' line threw up an error as R wasn't expecting one there. I clearly need to go and read more about the pipe and the way you use it here, and then will get to understanding the way the code here works. Thanks again.

**Comment by juliasilge** [comment]
It *is* a complicated bit of pipes/code right there, for sure. :pensive: One resource I really like for dplyr and the pipe (you may already know about it) is Garrett and Hadley's [book available online](http://r4ds.had.co.nz/).
