### ISSUE TITLE
Ch. 5 Typo: Fig 5-2 Caption

### ISSUE THREAD

**Issue by AndrewKostandy** [dgrtwo/tidy-text-mining#35]
The caption of figure 5-2 states it's computed as the product of the word's AFINN sentiment score and its frequency when it's actually using the Bing sentiment and counting the number of negative or positive sentiments a word has contributed. It does not compute the magnitude of those sentiments * frequency for each word.

**Comment by juliasilge** [comment]
Thank you so much! :raised_hands: I have also added this to [errata for the book at O'Reilly](http://www.oreilly.com/catalog/errata.csp?isbn=0636920067153). The first one, so.... yay?
