### ISSUE TITLE
Change title to "with R"?

### ISSUE THREAD

**Issue by dgrtwo** [dgrtwo/tidy-text-mining#4]
I've come around on changing to "with". My general reasoning is that most readers will think of R as a tool to accomplish something ("I did this; I did it with R") rather than something notable in itself ("I work in R; here's what I did").

Your thoughts?

**Comment by juliasilge** [comment]
Yeah, I probably could be convinced either way by strongly held arguments :stuck_out_tongue_winking_eye: but I think this is a good way to go. My initial instinct was for sure "in" but the more I look at it, the more I think "with" makes more sense. For examples, look how many of the O'Reilly R books say "with R":
http://shop.oreilly.com/category/browse-subjects/programming/r.do

**Comment by dgrtwo** [comment]
For me the O'Reilly link clinches it!
