### ISSUE TITLE
line / linenumber column name consistency in examples

### ISSUE THREAD

**Issue by martinjhnhadley** [dgrtwo/tidy-text-mining#43]
In the README for `tidytext` the column name for line numbers is called `linenumbers`:

https://github.com/juliasilge/tidytext
```r
original_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number()) %>%
  ungroup()
```

In a number of examples in the book the column is instead called `line`:

https://www.tidytextmining.com/tidytext.html
```r
library(dplyr)
text_df <- data_frame(line = 1:4, text = text)

text_df
```

This adds a tiny bit of friction to copying and pasting examples between the two resources. If there's interest I'll happily do the grunt work to make a pull request against the two to make them all consistent.

Hopefully you don't think this is a nitpick! tidytext is awesome and I really enjoy the book! I've observed some new R users get stuck when working with the text because of this issue, is all 🙂

**Comment by juliasilge** [comment]
Thanks for comment! If you have observed people having trouble, I bet others have as well. I decided to change the variable name in the README and vignette over on the tidytext repo in commit 85da3e67e834d1652a31ff5e4e27184d27e6ab4b.

**Comment by juliasilge** [comment]
I don't understand why linking is not working. 😩 It didn't successfully link either [my commit message over from the tidytext repo](https://github.com/juliasilge/tidytext/commit/85da3e67e834d1652a31ff5e4e27184d27e6ab4b) or the commit SHA from this repo.

**Comment by martinjhnhadley** [comment]
@juliasilge how odd, first time I've seen GitHub fail on that! Ohh, I see you've parcelled in a bunch of additional changes like `get_stopwords()` **noice** 😄
