### ISSUE TITLE
Unable to install janeaustenr

### ISSUE THREAD

**Issue by barrington1** [dgrtwo/tidy-text-mining#61]
Unable to install package=janeaustenr with R 3.4.1

**Comment by juliasilge** [comment]
Thanks for your interesting in janeaustenr @barrington1! 🙌 As of right now, this package should be [good to go for installation](https://cran.r-project.org/web/packages/janeaustenr/index.html). What kind of problem are you running into, specifically? Have you tried some of the [debugging options for this type of problem](https://stackoverflow.com/questions/25721884/how-should-i-deal-with-package-xxx-is-not-available-for-r-version-x-y-z-wa)?

**Comment by barrington1** [comment]
import.package ("https://CRAN.R-project.org/package=janeaustenr")Error in import.package("https://CRAN.R-project.org/package=janeaustenr") :   could not find function "import.package"> install.packages("C:/Users/bobby/Downloads/janeaustenr-master.zip", repos = NULL, type = "win.binary")Installing package into ‘C:/Users/bobby/Documents/R/win-library/3.5’(as ‘lib’ is unspecified)> janeaustenr-master::Error: unexpected end of line in "janeaustenr-master::"> library(janeaustenr)Error in library(janeaustenr) : there is no package called ‘janeaustenr’> library(dplyr)Error: package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called ‘rlang’> library(stringr)> library(`janeaustenr-master`)Error in library(`janeaustenr-master`) :   there is no package called ‘janeaustenr-master’> library(janeaustenr)Error in library(janeaustenr) : there is no package called ‘janeaustenr’

    On Tuesday, March 26, 2019, 3:35:46 PM CDT, Julia Silge <notifications@github.com> wrote:  
 
 
Thanks for your interesting in janeaustenr @barrington1! 🙌 As of right now, this package should be good to go for installation. What kind of problem are you running into, specifically? Have you tried some of the debugging options for this type of problem?

**Comment by juliasilge** [comment]
What happens if you type this in the R console?

```
install.packages("janeaustenr")
```

**Comment by barrington1** [comment]
Okay, 
install.packages("janeaustenr")Installing package into ‘C:/Users/bobby/Documents/R/win-library/3.5’(as ‘lib’ is unspecified)trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/janeaustenr_0.1.5.zip'Content type 'application/zip' length 1624986 bytes (1.5 MB)downloaded 1.5 MB
package ‘janeaustenr’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in C:\Users\bobby\AppData\Local\Temp\RtmpM9lDRo\downloaded_packages
Thanks, for the help!
Bobby


   On Tuesday, March 26, 2019, 6:57:18 PM CDT, Julia Silge <notifications@github.com> wrote: 
 
 
What happens if you type this in the R console?
install.packages("janeaustenr")

**Comment by juliasilge** [comment]
Great! Using `install.packages()` is the [most normal way to get packages from CRAN to your local machine](http://jtleek.com/modules/01_DataScientistToolbox/02_09_installingRPackages/#4).
