### ISSUE TITLE
Chapter 3 idf formula formatting issue

### ISSUE THREAD

**Issue by MikeJohnPage** [dgrtwo/tidy-text-mining#63]
The formula for calculating idf is not rendering properly on the [tidytextmining](https://www.tidytextmining.com/tfidf.html) site:

![Screenshot from 2019-05-06 16-09-50](https://user-images.githubusercontent.com/38110953/57206573-e2520f00-701a-11e9-90bb-cfd99db4ab8c.png)

I ran the [`03-tf-idf.Rmd`](https://github.com/dgrtwo/tidy-text-mining/blob/master/03-tf-idf.Rmd) file locally and had no issues, so I am not sure what is going on.

**Comment by juliasilge** [comment]
This is working for me today @MikeJohnPage. What about for you?

I did notice a problem for a few days with [MathJax](https://www.mathjax.org/) (the rendering engine that makes equations in this case) but it seems to be OK now?

**Comment by MikeJohnPage** [comment]
I didn't think to check different browsers, etc.

It is working in Firefox but not in Google Chrome (on Ubuntu 18.04). It is also working on Chrome on my Android phone. Must be a Ubuntu-Chrome specific issue.

**Comment by juliasilge** [comment]
I just checked Firefox, Safari, and Chrome on MacOS as well as Safari and Firefox on iOS, and it looked normal on all of those.

I did just double-check that I am using the latest MathJax in this project and it looks up-to-date.

**Comment by MikeJohnPage** [comment]
In that case, it must be an issue with my set-up. Thanks for looking into it.
