### ISSUE TITLE
tidytext 0.2.1 get_sentiments now needs interactive lexicon download and also removed NRC lexicon

### ISSUE THREAD

**Issue by eoayala** [dgrtwo/tidy-text-mining#64]
After updating tidytext package to version 0.2.1, changes in get_sentiments behaviour has broken code in 02-sentiment-analysis.Rmd (lines 38-40):

- now the get_sentiments() function expect to remotely download lexicon databases using the package textdata. Interactive prompt needed to be handled manually, before running the markdown code at first time

- NRC lexicon was removed (https://cran.r-project.org/web/packages/tidytext/news/news.html), so we have the following error:

> get_sentiments("nrc")
Error in match.arg(lexicon) : 
  'arg' should be one of “afinn”, “bing”, “loughran”

**Comment by juliasilge** [comment]
We have ✨ good news ✨ on this front, as the creators of the NRC lexicon have given permission for us to include their work in the [textdata](https://github.com/EmilHvitfeldt/textdata) package, the new way we are providing access to datasets like this. Once we add the dataset (tracked in EmilHvitfeldt/textdata#10) I will get this set back up to its original state.

**Comment by juliasilge** [comment]
The book now builds again. 🎉 

The book is written as if the user has already downloaded the datasets, as I think the interactive menu is pretty straightforward. If folks come with questions on this, I can adjust text in the book in the future.

The datasets are stored in `data/` in this repo, and the `.Rmd` files look for the datasets there.
