### ISSUE TITLE
Code issue?

### ISSUE THREAD

**Issue by apreshill** [dgrtwo/tidy-text-mining#65]
I was just browsing the online version of the book and noticed this block of code throughout the book at the top of each chapter- just wanted to make sure you were aware in case it was a weird Travis artifact that didn't show up locally: 
<img width="1084" alt="Screen Shot 2019-06-26 at 9 36 20 AM" src="https://user-images.githubusercontent.com/12160301/60199614-30a0b480-97f9-11e9-819b-b4d495fb3a8d.png">

**Comment by juliasilge** [comment]
Thanks for the heads up! 🙌 

I think what I need to do is

```r
suppressPackageStartupMessages(library(ggplot2))
```
in the first hidden chunk of each chapter.

As a reminder to myself, I need to wait to rebuild the book until I deal with #64 first.

**Comment by apreshill** [comment]
FYI @juliasilge- the same thing cropped up in the R packages book and the solution is to bump your ggplot2 version (I think!)

**Comment by juliasilge** [comment]
This is in fact fixed now, with the new version of ggplot2. Thank you! 🙏
