### ISSUE TITLE
Broken code in 9.1

### ISSUE THREAD

**Issue by arencambre** [dgrtwo/tidy-text-mining#67]
This code in section 9.1 cannot work:
```R
raw_text <- tibble(folder = dir(training_folder, full.names = TRUE)) %>%
  unnest(map(folder, read_folder)) %>%
  transmute(newsgroup = basename(folder), id, text)
```

**unnest** expects a data frame for its **data** argument ([source](https://tidyr.tidyverse.org/reference/unnest.html)), and **map** returns a **list** ([source](https://purrr.tidyverse.org/reference/map.html)).

Anyone using the code will get this error: **Error: `map(.$folder, read_folder)` must evaluate to column positions or names, not a list**.

Also, **unnest** requires specification of the **cols** argument, and that is not specified in the code.

**Comment by juliasilge** [comment]
Thank you so much for the report @arencambre! 🙌 This code I just pushed should fix the issue.

**Comment by arencambre** [comment]
Ah, breaking change in tidyr! I was wondering what the root cause was. 😁
