### ISSUE TITLE
Evaluation Error in 06. topic models

### ISSUE THREAD

**Issue by Kenjd** [dgrtwo/tidy-text-mining#68]
Hi Julia. I'm getting the following error when trying to run your code in lines 73-88. Actually, lines 73 to 80 run fine. But when I run 81-88 the following error appears (with no plot):

Error in mutate_impl(.data, dots) : 
  Evaluation error: could not find function "reorder_within".

Any help will be greatly appreciated.
And thanks for all your hard work and sharing.

**Comment by juliasilge** [comment]
Thanks so much for checking out the book @Kenjd! 🙌 

I believe you need to update to the current CRAN version of tidytext, using

```r
install.packages("tidytext")
```

You can see when that function was added [here](https://github.com/juliasilge/tidytext/blob/master/NEWS.md#tidytext-021), and you can read more about how to use it in [this blog post](https://juliasilge.com/blog/reorder-within/).
