### ISSUE TITLE
Sentiment lexicons have changed

### ISSUE THREAD

**Issue by arencambre** [dgrtwo/tidy-text-mining#74]
In **02-sentiment-analysis.Rmd**, the **get_sentiments(...)** function barks at you to use **textdata**. Once you have that, you must work through some interactive prompts the first time you use each lexicon. That is not reflected in the text.

**Comment by juliasilge** [comment]
Thanks so much @arencambre! I added some clarifying language, including:

> These lexicons are available under different licenses, so be sure that the license for the lexicon you want to use is appropriate for your project. You may be asked to agree to a license before downloading data.

**Comment by arencambre** [comment]
Thanks @juliasilge . While that text helps, the **textdata** package appears to be required for you to use some (all?) of these lexicons. I think the example code should load the **textdata** package right after **tidyverse**.

**Comment by juliasilge** [comment]
The textdata package is in `Suggests` for tidytext, so users don't need to load it. None of this code uses textdata functions directly.

**Comment by arencambre** [comment]
It is required for several lexicons:
```
> library(tidytext)
> get_sentiments("afinn")
Error: The textdata package is required to download the AFINN lexicon.
Install the textdata package to access this dataset.
> get_sentiments("bing")
# A tibble: 6,786 x 2
   word        sentiment
   <chr>       <chr>    
 1 2-faces     negative 
 2 abnormal    negative 
 3 abolish     negative 
 4 abominable  negative 
 5 abominably  negative 
 6 abominate   negative 
 7 abomination negative 
 8 abort       negative 
 9 aborted     negative 
10 aborts      negative 
# … with 6,776 more rows
> get_sentiments("nrc")
Error: The textdata package is required to download the NRC word-emotion association lexicon.
Install the textdata package to access this dataset.
> get_sentiments("loughran")
Error: The textdata package is required to download the Loughran-McDonald lexicon.
Install the textdata package to access this dataset.
```

**Comment by arencambre** [comment]
Sorry, I guess I could have worded this differently. I've experienced the rest of your book examples as being pretty turn-key: running the provided code produces the expected result, and if not, there is explanatory text.

In this case, there is a dependency that is not clearly explained in the text or code samples, which is that the **textdata** library needs to be installed. You are correct that it doesn't need to be loaded as a library (sorry for my mis-statement on that above), but it does need to be installed.

**Comment by juliasilge** [comment]
Thanks so much for this feedback @arencambre; I appreciate it. 

I'm going to think about the options here. My current opinion is that the explanatory text the user sees in the situation where they have installed tidytext but not textdata is quite clear about what step they need to take. However, there are changes we could make, such as moving textdata from `Suggests` to `Imports` in the way that [stopwords](https://github.com/juliasilge/tidytext/blob/5ac3248f230cd02aaed04ba9dd4428efa64dabb1/DESCRIPTION#L46) for example is `Imports`. Originally I decided to keep textdata as only `Suggests` because users of tidytext may not be interested in doing sentiment analysis.

**Comment by arencambre** [comment]
Interesting question. I haven't seen examples of where a package has a dependency that isn't installed along with the package, so I am shooting from the hip with ideas.

I read your concern being that this is a minor or less common use of **tidytext**? I checked **textdata**, and it's only ½ MB, so if it was just me, I'd make it **Imports**.

Alternatives:

- Detect presence of **textdata**. e.g., `"textdata" %in% installed.packages()[,"Package"]`. If not, either give friendly message and stop execution, or give user option to install **textdata**. While "just install it right here" has appeal, I'm assuming it would be poor form for a package to install another package without the user's permission.
- Separate sentiment analysis into its own package that will install all dependencies upon installation.
