### ISSUE TITLE
9.1 Preprocessing Error

### ISSUE THREAD

**Issue by walinchus** [dgrtwo/tidy-text-mining#88]
This line of code isn't working: 
`raw_text <- tibble(folder = dir(training_folder, full.names = TRUE))`
It says it does but it doesn't read anything. And yes I downloaded the folder so it's in there. I tried changing it to other folders but it didn't work. Does anyone know why?

**Comment by juliasilge** [comment]
This is related to #82. Be sure you have cloned the whole project and are working from the project directory. You might think about using a function like [`usethis::create_from_github()`](https://usethis.r-lib.org/reference/create_from_github.html).
