### ISSUE TITLE
Feature Request: Images of the data you are working with throughout the book

### ISSUE THREAD

**Issue by kputschko** [dgrtwo/tidy-text-mining#90]
Hey there, I love the book.  I come back to it every now and then when I need to do a text analysis from scratch.  I can follow your code easy enough to understand what it's doing generally, but it's challenging to know what the data going into the functions looks like without having to set up the entire script for myself.  

For example, if I want to recreate figure 1.3, I could do it easily enough on my end if I knew the exact layout of the data you were using for the plot.  But, it requires me to do the extra steps of recreating all your work before I can begin doing my work.

**Comment by juliasilge** [comment]
I think I need a bit of clarification @kputschko. Are you saying that [in this section](https://www.tidytextmining.com/tidytext.html#word-frequencies), you would find it more helpful to see `frequency` printed out before it is plotted for Figure 1.3?

**Comment by kputschko** [comment]
Thanks for the response.  Correct, seeing a snippet or glimpse of
`frequency` would help me conceptualize what exactly is being plotted,
given that my intuition around the `spread` and `gather` operations, in the
creation of `frequency`, has faded.
