### ISSUE TITLE
possible error with beginning of 'Case study: analyzing usenet text'

### ISSUE THREAD

**Issue by lukeEG** [dgrtwo/tidy-text-mining#91]
When running beginning of code to create raw_text tibble, I get the following error:
"Error: Problem with `mutate()` input `..2`.
x Input `..2` must be a vector, not a function.
i Input `..2` is `id`."

Package versions: 
tidyr=1.1.2; readr=1.4.0; purrr=0.3.4; dplyr=1.0.2

Thanks!

**Comment by juliasilge** [comment]
This is related to #82 and #88. Be sure you have cloned the whole project and are working from the project directory. You might think about using a function like [`usethis::create_from_github()`](https://usethis.r-lib.org/reference/create_from_github.html).

**Comment by lukeEG** [comment]
Ah ok, thank you for the explanation!
