### ISSUE TITLE
qualitative research

### ISSUE THREAD

**Issue by cmadland** [dgrtwo/tidy-text-mining#96]
Hello,
I'm just wondering if you know of anyone using this approach to analyze qualitative data in a research context. Thanks.

**Comment by juliasilge** [comment]
Thanks for your patience with this issue! Yes, folks have used this type of text mining to, for example, analyze free text survey questions and similar. You can see some examples of my own here:

- https://insights.stackoverflow.com/survey/2019#community-_-what-would-developers-change-about-stack-overflow
- https://stackoverflow.blog/2017/03/28/realistic-developer-fiction/

**Comment by juliasilge** [comment]
Let us know if you have further questions!
